Customers:
  class: Pantono\Customers\Customers
  parameters:
    - :Pantono\Customers\Repository\CustomersRepository
    - "@Hydrator"
    - "@EventDispatcher"
Companies:
  class: Pantono\Customers\Companies
